---
title: "課堂練習模版"
author: "DubiousJr"
date: "2020-12-09"
output: output_format
params:
  id: "410973017"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

####複製次數


```{r}
library(stringr)
```

```{r}
set.seed(2020)
d1 <- sample(c(rep("4",10),rep("3",3),rep("7",3)), 25, replace=T)
d2 <- sample(98:109, 25, replace=T)
d3 <- sample(c("73", "74", "78", "83", "72"))
d4 <- sample(1:120, 25, replace=T)
d4 <- str_pad(d4, 3, side = "left", pad="0")
schoolIds <- paste0(d1,d2,d3,d4)
schoolIds
```

```{r}
# {x} 前方卷帶連裝x條
str_subset(schoolIds,
           pattern='[0123456789]{9}')
str_subset(schoolIds,
           pattern='[0-9]{9}')
str_subset(schoolIds,
           pattern='[:digit:]{9}')

#從1~9內選九個數字
```

```{r}
myLove2R <- c("我實在是太愛太愛太愛愛R課程了",
  "我才是太愛太愛太太愛太太太愛R了",
  "我則是太愛愛太愛太愛愛愛R了",
  "找我太太聊天，我太太愛理不理的，我只好回去練我最愛的R。")
```

```{r}
str_view_all(myLove2R, "(太愛){2}")
#選連兩次“太愛”
```

```{r}
# {1,2} 前面卷帶裝1～2條 
str_view_all(myLove2R, "太[愛]{1,2}")
#找出太愛或太愛愛

str_view_all(myLove2R, "太愛{1,2}") # 卷帶只有一個字，可不寫[]

# ? 前面卷帶不確定要不要裝（要裝也只會裝1條）
str_view_all(myLove2R, "太愛[愛]?")
```

```{r}
#?=不確定有沒有0~1個
#愛全選
#有沒有愛都選
str_view_all(myLove2R, "太[愛]{1,}")
str_view_all(myLove2R, "太[愛]?")
str_view_all(myLove2R, "太[愛]+")
str_view_all(myLove2R, "太[愛]*")
```

```{r}
str_view_all(myLove2R, "太愛[愛]?")
```

```{r}
str_view_all(myLove2R, "太+愛+")
#不限幾愛幾愛
```

```{r}
str_view_all(myLove2R, "太+愛+(?!理不理)")
```

```{r}
addresses <- c(
  '臺中市后里區公館里尾社路385號',
  '新竹市東區科學園路125號1樓',
  '新竹市北區竹光路99號',
  '金門縣金城鎮賢庵里山前33號',
  '臺中市南屯區工業區二十四路23號1樓')
```

```{r}
str_extract(
  addresses,
  "[\u4E00-\u9FFF]+[區鎮]"
)
#包含中日韓文字（不限）但結尾一定為 區鎮

str_extract(
  addresses,
  "(?<=[縣市])[\u4E00-\u9FFF]+[區鎮]"
)
#目標前面一定是 市縣

str_extract(
  addresses,
  "(?<=[縣市])[^區]+[區鎮]"
)
#字元排除字元排除卷帶[^XYZ]：要排除的字元XYZ
```

```{r}

```

