---
title: "課堂練習模版"
author: "DubiousJr"
date: "2020-11-24"
output: output_format
params:
  id: "410973017"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code


4.5

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
str(example)
df_example<-as.data.frame(example)

```

```{r}
example$name[c(T, F, T, F)]#要不要向量
```

```{r}
str(example[c("name","height")])

#要不要向量
pick_above170 <- example$height >= 170 

example$height
c(175, 166, 170, 160) >= 170

example$name[pick_above170]
```
#####example內1998年以後(含)出生
```{r}
example$birthday
class(example$birthday)
typeof(example$birthday)
#比大小要確認是否相同class或type
```

```{r}
print(example[c("name","birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example$name[pick_after98]
```

######example內零用錢大於1000

```{r}
example$allowance>"2000"
```
```{r}
example$allowance %in% c("1000-2000","2000+")
```

```{r}
print(example[c("name","allowance")])
class(example$allowance)
levels(example$allowance)
pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
```
```{r}
example$allowance<-
  ordered(example$allowance)
levels(example$allowance)
```

```{r}
example$allowance
```

```{r}
allowance2<-factor("0-1000","1001-2000","2000+","1001-2000")
levels=c("1001-2000","0-1000","2000+")
allowance2<-ordered(allowance2)
allowance2
```

```{r}
example$allowance <- 
  ordered(example$allowance)
```

```{r}
example$allowance <-
  factor(
    example$allowance,
    levels=c("0-1000", "1001-2000", "2000+"),
    ordered = T # 設定為可排序factor
  )
```

```{r}
pick_allowanceOver1000 <- example$allowance >= "1001-2000"
example$name[pick_allowanceOver1000]
```

#####相等，屬於
```{r}
print(example[c("name","bloodType")])

pick_bloodB <- example$bloodType == "B"
example$name[pick_bloodB]
```
=，<- 是一樣的
```{r}
example$bloodType<-"B"
example$bloodType

df_exampleBloodType="B"
df_exampleBloodType
```

```{r}
7%%3 #餘數
```

```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
sequenceNums%%2
pick_evens <- (sequenceNums %% 2) == 0
sequenceNums[pick_evens]
```

#####誰來自大台北
```{r}
print(example[c("name","residence")])

set_TaipeiMetro <- c("Taipei","New Taipei")
pick_fromTaipeiMetro <- example$residence %in% set_TaipeiMetro
example$name[pick_fromTaipeiMetro]
```

```{r}
pick_not_fromTaipeiMetro <- ! pick_fromTaipeiMetro
# 或
pick_not_fromTaipeiMetro <- !(example$residence %in% set_TaipeiMetro) # (..) 裡面會先運算完才做外面!的處理
pick_fromTaipeiMetro
pick_not_fromTaipeiMetro
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
class(x2)
x2==NA #不能用這個找
is.na(x2)
```

```{r}
NaN
is.nan(x2)
```

```{r}
print(example[c("name","hobby")])

pick_loveFood <- stringr::str_detect(example$hobby,"美食")
example$name[pick_loveFood]
```

```{r}
str_detect(example$hobby,"美食")
#否定
!str_detect(example$hobby,"美食")

str_detect(example$hobby,"美食",negate = T)

```



4.6
```{r}
str(example)
pick_above170 <- example$height >= 170
pick_bloodB <- example$bloodType == "B"
pick_loveFood <- 
  stringr::str_detect(example$hobby,"美食")
pick_na <- is.na(example$weight)
pick_after98 <- 
  example$birthday >= lubridate::ymd("1998-01-01")
set_TaipeiMetro <- c("Taipei","New Taipei")
pick_fromTaipeiMetro <- 
  example$residence %in% set_TaipeiMetro
```
#####喜歡美食B型
```{r}
str(example[c("name","hobby","bloodType")])

example$name[
    pick_loveFood & pick_bloodB
  ]
```
#####誰1998以後（含）出生或不住大台北
```{r}
example[c("name","birthday","residence")]

example$name[
  pick_after98 | !pick_fromTaipeiMetro
]
```

####誰1998以後（含）出生且住大台北且血型B型
```{r}
example$name[
  pick_after98 & pick_fromTaipeiMetro & pick_bloodB
]
```

```{r}
pick_loveFood
pick_bloodB
pick_loveFood&pick_bloodB
```

######4.7

###parsing
```{r}
set.seed(2020)
ages_chr <- sample(c("4以下","5-10","11-15"), 15, replace=T)
ages_chr
```

```{r}
unique(ages_chr)
```

```{r}
table(ages_chr)
```

```{r}
factor(
  字面資訊向量
)
```

```{r}
ages_fct1 <- 
  factor(
    ages_chr
  )
```

```{r}
ages_chr
```

```{r}
ages_fct1
```

```{r}
table(ages_fct1)
table(ages_chr)
```

```{r}
factor(
  字面資訊向量,
  levels = 類別資訊呈現時的先後順序向量
)
```

```{r}
ages_fct2 <- 
  factor(
    ages_chr,
    levels = c("4以下","5-10","11-15")
  ) 
```

```{r}
table(ages_fct1)
table(ages_fct2)
```

```{r}
ages_fct2[[3]] #4以下
ages_fct2[[6]] #5-10
ages_fct2[[3]] > ages_fct2[[6]]
```
```{r}
ages_fct3 <- 
  factor(
    ages_chr,
    levels = c("4以下","5-10","11-15"),
    ordered = T
  )
```

```{r}
ages_fct3[[3]] #4以下
ages_fct3[[6]] #5-10
ages_fct3[[3]] > ages_fct3[[6]]
ages_fct3[[6]] < "11-15" # 也可以用文字寫下levels中有的分類
```

```{r}
levels(ages_fct3)
ages_fct3[[3]]<"5-10"
age_fct6[[3]]<"5-15"
```

```{r}
ages_fct2 #levels
```

```{r}
# 忘了告訴電腦是ordered factor
ages_fct2_order = factor(ages_fct2, ordered=T)
ages_fct2_order
# 也可以
ages_fct2_order = as.ordered(ages_fct2)

# 忘了告訴電腦呈現順序是"11-15","5-10","4以下"
ages_fct3_newLevels = 
  factor(
    ages_fct3, 
    levels = c("11-15","5-10","4以下")
  )
ages_fct3_newLevels
is.ordered(ages_fct3_newLevels)
```

